services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: gafer
      POSTGRES_PASSWORD: gafer
      POSTGRES_DB: gafer
    ports:
      - '5432:5432'
    volumes:
      - gafer_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - gafer_redis_data:/data

  minio:
    image: quay.io/minio/minio:latest
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: gafer
      MINIO_ROOT_PASSWORD: gafersecret
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - gafer_minio_data:/data

volumes:
  gafer_postgres_data:
  gafer_redis_data:
  gafer_minio_data:
