services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: gafer
      POSTGRES_PASSWORD: gafer
      POSTGRES_DB: gafer
    ports:
      - '5432:5432'
    volumes:
      - gafer_postgres_data:/var/lib/postgresql/data

volumes:
  gafer_postgres_data:
