import type { DocumentoDetalle, DocumentoResumen } from './tipos';

/**
 * Con la decisión C8 el cierre pasa directo a revisión: en la web no hay
 * documentos CERRADO. Los BORRADOR siguen en campo, en la app del técnico.
 */
export const DOCUMENTOS_MOCK: DocumentoResumen[] = [
  { id: 'd1', codigo: 'INFORME-KALLPA-014-2026', cliente: 'KALLPA', proyecto: 'PLANTA', tipo: 'INFORME', estado: 'ENVIADO_A_REVISION', fecha: '2026-09-15' },
  { id: 'd2', codigo: 'REPORTE-KALLPA-005-2026', cliente: 'KALLPA', proyecto: 'CSF_SUNNY', tipo: 'REPORTE', estado: 'ENVIADO_A_REVISION', fecha: '2026-09-16' },
  { id: 'd3', codigo: 'INFORME-SAMAY-031-2026', cliente: 'SAMAY', proyecto: 'ALMACEN', tipo: 'INFORME', estado: 'OBSERVADO', fecha: '2026-09-14' },
  { id: 'd4', codigo: 'INFORME-PETROPERU-002-2026', cliente: 'PETROPERU', proyecto: 'REFINERIA_NORTE', tipo: 'INFORME', estado: 'APROBADO', fecha: '2026-09-12' },
  { id: 'd5', codigo: 'REPORTE-VARIOS-118-2026', cliente: 'VARIOS', proyecto: 'MINA_ANDINA', tipo: 'REPORTE', estado: 'ENVIADO', fecha: '2026-09-10' },
  { id: 'd6', codigo: 'INFORME-KALLPA-013-2026', cliente: 'KALLPA', proyecto: 'PLANTA', tipo: 'INFORME', estado: 'ENVIADO_A_REVISION', fecha: '2026-09-17' },
  { id: 'd7', codigo: 'INFORME-SAMAY-030-2026', cliente: 'SAMAY', proyecto: 'ALMACEN', tipo: 'INFORME', estado: 'BORRADOR', fecha: '2026-09-17' },
];

const resumen = (id: string) => DOCUMENTOS_MOCK.find((d) => d.id === id)!;

export const DOCUMENTOS_DETALLE_MOCK: Record<string, DocumentoDetalle> = {
  d1: {
    ...resumen('d1'),
    diagnostico: 'Presencia moderada de roedores en zona de almacén de insumos. Sin evidencia de plagas rastreras.',
    trabajosRealizados: 'Desratización perimetral e interior según programa quincenal. Reposición de cebo en 6 estaciones.',
    insumosUsados: [
      { producto: 'Brodifacoum 0.005% bloque', lote: 'L-2451', cantidad: '600 g', concentracion: '0.005%' },
      { producto: 'Cipermetrina 25% EC', lote: 'L-2298', cantidad: '2 L', concentracion: '10 ml/L' },
    ],
    personal: [
      { nombre: 'Marco Ipusari', cargo: 'Técnico Operador' },
      { nombre: 'Diana Amamani', cargo: 'Supervisor' },
    ],
    accionesCorrectivas: ['Sellado de perforación en muro sur', 'Reubicación de estación 04 por acceso restringido'],
    observaciones: 'Acceso a zona de tanques restringido por mantenimiento programado, se reprograma para próxima visita.',
    recomendaciones: 'Mantener orden y limpieza en almacén de insumos, retirar cartones acumulados junto a estación 06.',
    fotos: 8,
    fotosRecibidas: 5,
    numeroCertificado: 'CERT-KALLPA-014-2026',
    vencimientoCertificado: '2026-12-15',
    firmaCliente: 'Rosa Contreras — Jefa de Planta',
  },
  d2: {
    ...resumen('d2'),
    diagnostico: 'Actividad baja en perímetro; dos estaciones con consumo en zona de despacho.',
    trabajosRealizados: 'Inspección de 18 estaciones del Mapa Murino y reposición de cebo donde hubo consumo.',
    insumosUsados: [{ producto: 'Brodifacoum 0.005% bloque', lote: 'L-2460', cantidad: '240 g', concentracion: '0.005%' }],
    personal: [{ nombre: 'Jorge Huamán', cargo: 'Técnico Operador' }],
    accionesCorrectivas: ['Refuerzo de cebado'],
    observaciones: 'Estación 12 con cuarta visita consecutiva con consumo.',
    recomendaciones: 'Retirar residuos orgánicos del área de despacho.',
    fotos: 24,
    numeroCertificado: 'CERT-KALLPA-005-2026',
    vencimientoCertificado: '2026-10-16',
    firmaCliente: 'Luis Rojas — Jefe de Planta',
  },
  d3: {
    ...resumen('d3'),
    diagnostico: 'Actividad de roedores en incremento en zona de carga.',
    trabajosRealizados: 'Desratización según contrato mensual.',
    insumosUsados: [{ producto: 'Bromadiolona 0.005% pellet', lote: 'L-2510', cantidad: '400 g', concentracion: '0.005%' }],
    personal: [{ nombre: 'Jorge Huamán', cargo: 'Técnico Operador' }],
    accionesCorrectivas: ['Colocación de estación adicional en zona de carga'],
    observaciones: 'Estación 09 sin fotografía.',
    recomendaciones: 'Retirar residuos orgánicos acumulados junto al ingreso de carga.',
    fotos: 5,
    numeroCertificado: 'CERT-SAMAY-031-2026',
    vencimientoCertificado: '2026-11-30',
    firmaCliente: 'Luis Beltrán — Jefe de Almacén',
    comentarioObservacion: 'Falta fotografía de estación 09 y el detalle de la zona de carga.',
  },
  d4: {
    ...resumen('d4'),
    diagnostico: 'Condición sanitaria aceptable; sin evidencia de plagas en áreas de proceso.',
    trabajosRealizados: 'Desinfección de oficinas y comedor por nebulización.',
    insumosUsados: [{ producto: 'Hipoclorito de sodio 7.5%', lote: 'L-3120', cantidad: '5 L', concentracion: '7.5%' }],
    personal: [{ nombre: 'Marco Ipusari', cargo: 'Técnico Operador' }],
    accionesCorrectivas: [],
    observaciones: 'Sin observaciones.',
    recomendaciones: 'Mantener ventilación del comedor después del servicio.',
    fotos: 6,
    fotosSeleccionadas: [0, 1, 2, 3, 4, 5],
    numeroCertificado: 'CERT-PETROPERU-002-2026',
    vencimientoCertificado: '2026-12-12',
    firmaCliente: 'Ana Quispe — Jefa de Seguridad',
    firmaDirector: 'Ing. Carlos Medina Ruiz · CIP 84512',
    generados: ['INFORME-PETROPERU-002-2026.pdf', 'CERT-PETROPERU-002-2026.pdf'],
    anexos: ['Ficha técnica — Hipoclorito de sodio 7.5%', 'MSDS — Hipoclorito de sodio 7.5%', 'Resolución de licencia sanitaria de GAFER'],
  },
  d5: {
    ...resumen('d5'),
    diagnostico: 'Actividad nula en campamento.',
    trabajosRealizados: 'Inspección de 12 estaciones sin consumo.',
    insumosUsados: [{ producto: 'Bromadiolona 0.005% pellet', lote: 'L-2510', cantidad: '120 g', concentracion: '0.005%' }],
    personal: [{ nombre: 'Luis Beltrán', cargo: 'Técnico Operador' }],
    accionesCorrectivas: [],
    observaciones: 'Sin observaciones.',
    recomendaciones: 'Mantener orden en almacén de víveres.',
    fotos: 4,
    fotosSeleccionadas: [0, 1, 2, 3],
    numeroCertificado: '—',
    vencimientoCertificado: '—',
    firmaCliente: 'Responsable no disponible al momento del servicio',
    firmaDirector: 'Ing. Carlos Medina Ruiz · CIP 84512',
    generados: ['REPORTE-VARIOS-118-2026.pdf'],
    anexos: ['Ficha técnica — Bromadiolona 0.005% pellet', 'MSDS — Bromadiolona 0.005% pellet', 'Resolución de licencia sanitaria de GAFER'],
  },
  d6: {
    ...resumen('d6'),
    diagnostico: 'Presencia leve de insectos rastreros en cocina.',
    trabajosRealizados: 'Desinsectación por aspersión en cocina y almacén.',
    insumosUsados: [{ producto: 'Cipermetrina 25% EC', lote: 'L-2298', cantidad: '1 L', concentracion: '10 ml/L' }],
    personal: [{ nombre: 'Marco Ipusari', cargo: 'Técnico Operador' }],
    accionesCorrectivas: ['Sellado de grietas en zócalos'],
    observaciones: 'Cliente solicita repetir en 15 días.',
    recomendaciones: 'Reparar tuberías con fuga bajo el lavadero.',
    fotos: 3,
    numeroCertificado: 'CERT-KALLPA-013-2026',
    vencimientoCertificado: '2026-12-17',
    firmaCliente: 'Rosa Contreras — Jefa de Planta',
  },
  d7: {
    ...resumen('d7'),
    diagnostico: '',
    trabajosRealizados: '',
    insumosUsados: [],
    personal: [{ nombre: 'Jorge Huamán', cargo: 'Técnico Operador' }],
    accionesCorrectivas: [],
    observaciones: '',
    recomendaciones: '',
    fotos: 0,
    numeroCertificado: '—',
    vencimientoCertificado: '—',
    firmaCliente: '—',
  },
};
